modLoader="javafml"
loaderVersion=""
license="MIT"
#issueTrackerURL="https://github.com/MyOrganization/MyMod/" #optional
clientSideOnly=true

[[mods]]
modId="transformableitems"
version="1.0.0"
displayName="Transformable Items"
logoFile="transformableitems.png"
authors="shaweel"
description="Lets you move and resize held items"

[[dependencies.transformableitems]]
	modId="forge"
	mandatory=true
	versionRange="[64,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.transformableitems]]
	modId="minecraft"
	mandatory=true
	versionRange="[26.1,26.1.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.transformableitems]]
	modId="clothconfig"
	mandatory=true
	versionRange=""
	ordering="NONE"
	side="BOTH"